import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from 'next/link' 

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        
         <>
          <div
            className = 'grid grid-cols-3 m-3 gap-x-3 text-white p-2 text-2xl'
          >
            <Link
              href = {'/'}
              className='px-5 bg-gray-600 rounded-md text-center'
            >
              Home
            </Link>

            <Link
              href = {'/about'}
              className='px-5 bg-gray-600 rounded-md text-center'
          
            >
              About
            </Link>

            <Link
              href={'/career'}
              className='px-5 bg-gray-600 rounded-md text-center'
            >
              Careers
            </Link>
          </div>
          {children}
        </>
      </body>
    </html>
  );
}
