'use-client'
import Link from "next/link";

import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Ecommerce Platform",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header
          className="flex justify-around text-2xl font-bold p-2 m-2 bg-gray-200 text-blue-950 rounded-xl"
        >
          <div>
            Ecommerce
          </div>
          <div>
            <ul
              className ='flex gap-10'
            >
              <li>Home</li>
              <li>Products</li>
              <li>Login/Register</li>
            </ul>
          </div>
        </header>
        {children}
      
      </body>
    </html>
  );
}
