// import Link from "next/link";
// import {ShoppingCart } from 'lucide-react'

// import {  Allura, IBM_Plex_Serif, Playfair_Display, Kalnia, Cause } from "next/font/google";
// import "./globals.css";

// import { myFont } from "./font";

// const allura = Kalnia({
//   variable : '--font-allura',
//   subsets: ["latin"],
//   weight : '400'
// });

// export const metadata = {
//   title: "Ecommerce Platform",
//   description: "Generated by create next app",
// };

// import Cart from "./cart";

// import ReduxProvider from "@/providers/ReduxProvider";


// export default function RootLayout({ children }) {
  
//   return (
//     <html lang="en">
//       <body
//         className={`${myFont.className}  antialiased`}
//       >
        
//         <ReduxProvider>
//           <header
//             className="
//               flex justify-around 
//               text-2xl font-bold 
//               p-2 m-2 bg-gray-200 
//               text-blue-950 rounded-xl
//               sticky top-0 z-50 opacity-90
//               "
//           >
//             <div>
//               Ecommerce
//             </div>
//             <div>
//               <ul
//                 className ='flex gap-10'
//               >
//                 <li>Home</li>
//                 <li>Products</li>
//                 <li className = 'flex'> 
//                       <Cart/> 
//                   <ShoppingCart className=" m-1 " /></li>
//                 <li>Login/Register</li>
//               </ul>
//             </div>
//           </header>
//           {children}
//         </ReduxProvider>
      
//       </body>
//     </html>
//   );
// }
import Link from "next/link";
import { ShoppingCart } from "lucide-react";
import { Kalnia } from "next/font/google";
import "./globals.css";

import { myFont } from "./font";
import Cart from "./cart";
import ReduxProvider from "@/providers/ReduxProvider";
import Footer from "@/components/footer";


const allura = Kalnia({
  variable: "--font-allura",
  subsets: ["latin"],
  weight: "400",
});

export const metadata = {
  title: "Ecommerce Platform",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${myFont.className} antialiased`}>
        <ReduxProvider>
          <header
            className="
              flex justify-around 
              text-2xl font-bold 
              p-2 m-2 bg-gray-200 
              text-blue-950 rounded-xl
              sticky top-0 z-50 opacity-90
            "
          >
            <div>Ecommerce</div>
            <div>
              <ul className="flex gap-10">
                <li>Home</li>
                <li>Products</li>
                <li className="flex">
                  <Cart />
                  <ShoppingCart className="m-1" />
                </li>
                <li>Login/Register</li>
              </ul>
            </div>
          </header>

          {/* Main content */}
          {children}

          {/* Footer */}
          <Footer/>
        </ReduxProvider>
      </body>
    </html>
  );
}