'use-client'
import Link from "next/link";

import {  Allura, IBM_Plex_Serif, Playfair_Display, Kalnia, Cause } from "next/font/google";
import "./globals.css";

import { myFont } from "./font";

const allura = Kalnia({
  variable : '--font-allura',
  subsets: ["latin"],
  weight : '400'
});

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata = {
  title: "Ecommerce Platform",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${myFont.className}  antialiased`}
      >
        <header
          className="
            flex justify-around 
            text-2xl font-bold 
            p-2 m-2 bg-gray-200 
            text-blue-950 rounded-xl
            sticky top-0 z-50 opacity-90
            "
        >
          <div>
            Ecommerce
          </div>
          <div>
            <ul
              className ='flex gap-10'
            >
              <li>Home</li>
              <li>Products</li>
              <li>Login/Register</li>
            </ul>
          </div>
        </header>
        {children}
      
      </body>
    </html>
  );
}
